/**
 * How to FIND buildings on the map — not just their internal loot names.
 */
const GUIDE_BUILDINGS = {
  _world: {
    title: 'Vanilla world spawn',
    find: 'This loot is not at one GPS pin. The game rolls it inside matching buildings anywhere on the Kentucky map (and mod maps using vanilla distribution). Open the map (M) and search towns for the building types below.',
    identify: 'Loot is inside containers (shelves, lockers, crates) — search the whole building.',
    areas: 'Louisville, West Point, Muldraugh, Riverside, Rosewood, March Ridge, highways, rural sites',
  },
  blacksmith: {
    title: 'Blacksmith / forge shop',
    find: 'Look for shops with an outdoor forge or anvil. Louisville has several along the south/west industrial belt; smaller towns may have one near the main strip.',
    identify: 'Outdoor forge, anvil, metal shelves, blowtorches, welding masks',
    areas: 'Louisville industrial outskirts, March Ridge, Riverside docks, rural highway shops',
  },
  metalfabrication: {
    title: 'Metal fabrication workshop',
    find: 'Factory-style metal shops in industrial parks — larger than a blacksmith.',
    identify: 'Industrial zoning, metal shelves, tool cabinets',
    areas: 'Louisville industrial district, factory zones',
  },
  metalfabricationstorage: {
    title: 'Metal fabrication storage',
    find: 'Back room or warehouse attached to metal fabrication buildings.',
    identify: 'Crates and metal shelves behind fabrication workshop',
    areas: 'Industrial areas with fabrication workshops',
  },
  metalshop: {
    title: 'Factory metal shop',
    find: 'Metalworking corner inside large factory complexes.',
    identify: 'Factory floor with metal shelves in a side room',
    areas: 'Factory and logging districts',
  },
  toolstore: {
    title: 'Hardware / tool store',
    find: 'Retail hardware stores on main streets — Handy Hardware style buildings.',
    identify: 'Tool displays, front counter, parking lot',
    areas: 'Main street in Muldraugh, West Point, Riverside, Louisville',
  },
  toolstorestorage: {
    title: 'Tool store back room',
    find: 'Storage area behind a hardware store counter.',
    identify: 'Same building as hardware store',
    areas: 'Attached to hardware stores',
  },
  garage: {
    title: 'Residential garage',
    find: 'Garages attached to suburban houses.',
    identify: 'Garage door, workbench, shelves',
    areas: 'Suburbs in Riverside, Louisville, Rosewood',
  },
  garagestorage: {
    title: 'Storage locker facility',
    find: 'Fenced U-Store It style buildings with many small rental units.',
    identify: 'Row of small garage doors, office counter',
    areas: 'Louisville outskirts, Muldraugh, near highways',
  },
  storageunit: {
    title: 'Rented storage unit',
    find: 'Individual units inside a storage locker facility.',
    identify: 'Small indoor units within storage facilities',
    areas: 'Inside storage locker facilities',
  },
  gunstore: {
    title: 'Gun store (shop floor)',
    find: 'Licensed gun shops — Louisville, West Point, and Riverside each have marked gun stores.',
    identify: 'Gun displays, ammo boxes, shooting target decor',
    areas: 'Louisville (multiple), West Point, Riverside, Valley Station',
  },
  gunstorestorage: {
    title: 'Gun store back room',
    find: 'Secure storage behind the gun shop sales floor.',
    identify: 'Military lockers and ammo crates behind shop',
    areas: 'Attached to gun stores',
  },
  armystorage: {
    title: 'Army storage building',
    find: 'Military base warehouses — Louisville military sites and mod military maps.',
    identify: 'Camo netting, military crates, fenced compounds',
    areas: 'Louisville military POIs, army areas on mod maps',
  },
  armyhangar: {
    title: 'Army hangar',
    find: 'Large hangars on military airfield POIs.',
    identify: 'Huge hangar buildings, military vehicles',
    areas: 'Military airfields',
  },
  armysurplus: {
    title: 'Army surplus store',
    find: 'Civilian retail selling camo and military gear.',
    identify: 'Camo racks, military-themed retail',
    areas: 'Commercial strips in larger towns',
  },
  policestorage: {
    title: 'Police evidence / storage',
    find: 'Back rooms of police stations in every town with a PD.',
    identify: 'Police HQ building, evidence lockers',
    areas: 'West Point, Riverside, Louisville, Rosewood police stations',
  },
  policegunstorage: {
    title: 'Police gun storage',
    find: 'Armory inside larger police stations.',
    identify: 'Weapon lockers in secure police area',
    areas: 'Large police HQs',
  },
  policeswat: {
    title: 'Police SWAT armory',
    find: 'SWAT weapons room in major police facilities.',
    identify: 'Heavy weapon lockers, SWAT gear',
    areas: 'Louisville PD and large-city police',
  },
  hunting: {
    title: 'Hunting lodge / shop',
    find: 'Woodland hunting stores near forests — deer mounts and camo.',
    identify: 'Trophy animals, rifles on wall, camo',
    areas: 'Forest town edges, Ekron, rural areas',
  },
  hunterstorage: {
    title: 'Hunter storage shed',
    find: 'Shed beside hunting lodges.',
    identify: 'Wooden shed near hunting shop',
    areas: 'Near hunting lodges',
  },
  warehouse: {
    title: 'Warehouse',
    find: 'Large industrial warehouses — Louisville docks, logistics parks.',
    identify: 'Loading bays, metal shelves, open floor',
    areas: 'Industrial districts',
  },
  mechanic: {
    title: 'Auto mechanic shop',
    find: 'Gas station garages and standalone mechanics with lifts.',
    identify: 'Car lifts, tool chests, tires',
    areas: 'Gas stations and mechanic strips',
  },
  gasstore: {
    title: 'Gas station shop',
    find: 'Convenience store at gas stations — very common on highways.',
    identify: 'Gas pumps outside, small retail inside',
    areas: 'Highways and every town',
  },
  pharmacy: {
    title: 'Pharmacy',
    find: 'Drug stores in commercial districts.',
    identify: 'Pharmacy sign, medicine shelves',
    areas: 'Town commercial districts',
  },
  medical: {
    title: 'Medical clinic',
    find: 'Doctor offices and small clinics.',
    identify: 'Medical signage, exam rooms',
    areas: 'Towns near hospitals',
  },
  medicalstorage: {
    title: 'Hospital storage',
    find: 'Back rooms of hospitals — Louisville medical campus is largest.',
    identify: 'Hospital complex, medicine crates',
    areas: 'Louisville hospital, clinics',
  },
  construction: {
    title: 'Construction site office',
    find: 'Trailers at construction POIs on the map.',
    identify: 'Scaffolding, portable office trailer',
    areas: 'Construction sites',
  },
  shed: {
    title: 'Garden shed',
    find: 'Backyard sheds at houses and garden stores.',
    identify: 'Small outbuilding, garden tools',
    areas: 'Residential and garden stores',
  },
  gardenstore: {
    title: 'Garden supply store',
    find: 'Gardening retail with plants and tools.',
    identify: 'Greenhouse tiles, plant trays',
    areas: 'Commercial strips',
  },
  farmingstore: {
    title: 'Farming supply store',
    find: 'Ag supply near farmland.',
    identify: 'Feed bags, farming tools',
    areas: 'Ekron, farmland, rural highways',
  },
  pawnshopoffice: {
    title: 'Pawn shop',
    find: 'Pawn shops in commercial districts.',
    identify: 'Pawn signage, glass cases',
    areas: 'Louisville and larger towns',
  },
  pawnshopstorage: {
    title: 'Pawn shop storage',
    find: 'Back room of pawn shops.',
    identify: 'Connected to pawn shop',
    areas: 'With pawn shops',
  },
  captainoffice: {
    title: 'Police captain office',
    find: 'Upstairs or secure wing of larger police stations.',
    identify: 'Desk, filing cabinets, police signage',
    areas: 'Louisville PD, large-town police HQs',
  },
  kitchen: {
    title: 'Restaurant / commercial kitchen',
    find: 'Back kitchen of restaurants, diners, and food shops.',
    identify: 'Stoves, fridges, prep counters',
    areas: 'Restaurant rows in every town, Spiffo\'s, diners',
  },
  restaurantkitchen: {
    title: 'Restaurant kitchen',
    find: 'Kitchen area behind restaurant dining rooms.',
    identify: 'Commercial stoves, walk-in coolers',
    areas: 'Urban restaurant districts',
  },
  spiffokitchen: {
    title: "Spiffo's kitchen",
    find: 'Spiffo\'s fast food locations — kitchen behind counter.',
    identify: 'Spiffo\'s mascot decor, fast food kitchen',
    areas: 'Spiffo\'s in Louisville, West Point, Muldraugh',
  },
  motelroom: {
    title: 'Motel room',
    find: 'Motel buildings along highways and town edges.',
    identify: 'Motel sign, row of small rooms, parking lot',
    areas: 'Highway motels, outskirts of towns',
  },
  hotelroom: {
    title: 'Hotel room',
    find: 'Hotels in Louisville and larger towns.',
    identify: 'Multi-floor hotel, lobby, room keys',
    areas: 'Louisville downtown, Riverside',
  },
  zippeestore: {
    title: 'Zippee market back room',
    find: 'Convenience stores (Zippee) — back storage room.',
    identify: 'Zippee branding, small grocery',
    areas: 'Common in all towns',
  },
  laundry: {
    title: 'Laundromat',
    find: 'Coin laundromats in commercial strips.',
    identify: 'Washing machines, dryers, folding tables',
    areas: 'Town commercial areas',
  },
  classroom: {
    title: 'School classroom',
    find: 'School buildings in Rosewood, West Point, Louisville.',
    identify: 'Desks, chalkboards, lockers in halls',
    areas: 'School POIs in towns',
  },
  firestorage: {
    title: 'Fire station storage',
    find: 'Fire stations — gear storage room.',
    identify: 'Fire trucks, hoses, turnout gear',
    areas: 'Fire stations in most towns',
  },
  camping: {
    title: 'Camping store',
    find: 'Outdoor / camping retail shops.',
    identify: 'Tents, sleeping bags, camping gear displays',
    areas: 'Commercial strips, near highways',
  },
  campingstorage: {
    title: 'Camping store storage',
    find: 'Back room of camping supply stores.',
    identify: 'Attached to camping stores',
    areas: 'With camping stores',
  },
  fishingstorage: {
    title: 'Fishing supply storage',
    find: 'Back room of fishing / bait shops.',
    identify: 'Near docks or fishing retail',
    areas: 'Riverside, Ekron, waterfront towns',
  },
  security: {
    title: 'Security office',
    find: 'Mall security, office building security desks.',
    identify: 'Security desk, monitors, badge readers',
    areas: 'Malls, offices, Louisville commercial',
  },
  loggingfactory: {
    title: 'Logging factory',
    find: 'Large lumber processing plants in forest industrial zones.',
    identify: 'Log piles, saws, industrial lumber equipment',
    areas: 'Muldraugh forest industrial area',
  },
  factory: {
    title: 'Factory floor',
    find: 'Large factory complexes in industrial districts.',
    identify: 'Assembly lines, forklifts, factory floor tiles',
    areas: 'Louisville industrial, factory zones',
  },
  all: {
    title: 'Map-wide military locker pool',
    find: 'Can appear in military lockers across many military buildings — not one fixed building.',
    identify: 'Military lockers in bases and checkpoints',
    areas: 'Military POIs server-wide',
  },
};
